//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ma {
            get {
                return this.maField;
            }
            set {
                if ((object.ReferenceEquals(this.maField, value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.getAllResponse getAll(WindowsFormsApp1.ServiceReference1.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getAllResponse> getAllAsync(WindowsFormsApp1.ServiceReference1.getAllRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStudent", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.addStudentResponse addStudent(WindowsFormsApp1.ServiceReference1.addStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.addStudentResponse> addStudentAsync(WindowsFormsApp1.ServiceReference1.addStudentRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteStudent", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.deleteStudentResponse deleteStudent(WindowsFormsApp1.ServiceReference1.deleteStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.deleteStudentResponse> deleteStudentAsync(WindowsFormsApp1.ServiceReference1.deleteStudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(WindowsFormsApp1.ServiceReference1.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRequestBody {
        
        public getAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(WindowsFormsApp1.ServiceReference1.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.Student[] getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(WindowsFormsApp1.ServiceReference1.Student[] getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudent", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.addStudentRequestBody Body;
        
        public addStudentRequest() {
        }
        
        public addStudentRequest(WindowsFormsApp1.ServiceReference1.addStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ten;
        
        public addStudentRequestBody() {
        }
        
        public addStudentRequestBody(string ma, string ten) {
            this.ma = ma;
            this.ten = ten;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.addStudentResponseBody Body;
        
        public addStudentResponse() {
        }
        
        public addStudentResponse(WindowsFormsApp1.ServiceReference1.addStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.Student addStudentResult;
        
        public addStudentResponseBody() {
        }
        
        public addStudentResponseBody(WindowsFormsApp1.ServiceReference1.Student addStudentResult) {
            this.addStudentResult = addStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteStudent", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.deleteStudentRequestBody Body;
        
        public deleteStudentRequest() {
        }
        
        public deleteStudentRequest(WindowsFormsApp1.ServiceReference1.deleteStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        public deleteStudentRequestBody() {
        }
        
        public deleteStudentRequestBody(string ma) {
            this.ma = ma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.deleteStudentResponseBody Body;
        
        public deleteStudentResponse() {
        }
        
        public deleteStudentResponse(WindowsFormsApp1.ServiceReference1.deleteStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteStudentResponseBody {
        
        public deleteStudentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.getAllResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.getAll(WindowsFormsApp1.ServiceReference1.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.Student[] getAll() {
            WindowsFormsApp1.ServiceReference1.getAllRequest inValue = new WindowsFormsApp1.ServiceReference1.getAllRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.getAllRequestBody();
            WindowsFormsApp1.ServiceReference1.getAllResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getAllResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.getAllAsync(WindowsFormsApp1.ServiceReference1.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getAllResponse> getAllAsync() {
            WindowsFormsApp1.ServiceReference1.getAllRequest inValue = new WindowsFormsApp1.ServiceReference1.getAllRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.getAllRequestBody();
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).getAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.addStudentResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.addStudent(WindowsFormsApp1.ServiceReference1.addStudentRequest request) {
            return base.Channel.addStudent(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.Student addStudent(string ma, string ten) {
            WindowsFormsApp1.ServiceReference1.addStudentRequest inValue = new WindowsFormsApp1.ServiceReference1.addStudentRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.addStudentRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            WindowsFormsApp1.ServiceReference1.addStudentResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).addStudent(inValue);
            return retVal.Body.addStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.addStudentResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.addStudentAsync(WindowsFormsApp1.ServiceReference1.addStudentRequest request) {
            return base.Channel.addStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.addStudentResponse> addStudentAsync(string ma, string ten) {
            WindowsFormsApp1.ServiceReference1.addStudentRequest inValue = new WindowsFormsApp1.ServiceReference1.addStudentRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.addStudentRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).addStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.deleteStudentResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.deleteStudent(WindowsFormsApp1.ServiceReference1.deleteStudentRequest request) {
            return base.Channel.deleteStudent(request);
        }
        
        public void deleteStudent(string ma) {
            WindowsFormsApp1.ServiceReference1.deleteStudentRequest inValue = new WindowsFormsApp1.ServiceReference1.deleteStudentRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.deleteStudentRequestBody();
            inValue.Body.ma = ma;
            WindowsFormsApp1.ServiceReference1.deleteStudentResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).deleteStudent(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.deleteStudentResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.deleteStudentAsync(WindowsFormsApp1.ServiceReference1.deleteStudentRequest request) {
            return base.Channel.deleteStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.deleteStudentResponse> deleteStudentAsync(string ma) {
            WindowsFormsApp1.ServiceReference1.deleteStudentRequest inValue = new WindowsFormsApp1.ServiceReference1.deleteStudentRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.deleteStudentRequestBody();
            inValue.Body.ma = ma;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).deleteStudentAsync(inValue);
        }
    }
}
